Vs = getsampleusingtime(logsout.get('V.s').Values, tstart, tstop);
Vs_a = Vs;
Vs_a.Data = Vs.Data(:, 1);
Vs_b = Vs;
Vs_b.Data = Vs.Data(:, 2);
Vs_c = Vs;
Vs_c.Data = Vs.Data(:, 3);
Is = getsampleusingtime(logsout.get('I.s').Values, tstart, tstop);
Is_a = Is;
Is_a.Data = Is.Data(:, 1);
Is_b = Is;
Is_b.Data = Is.Data(:, 2);
Is_c = Is;
Is_c.Data = Is.Data(:, 3);
Vd = getsampleusingtime(logsout.get('V.d').Values, tstart, tstop);
Id = getsampleusingtime(logsout.get('I.d').Values, tstart, tstop);
S_volts = cell(6, 1);
S_amps = cell(6, 1);
for n = 1:6
    s1 = strcat('S', num2str(n));
    S_volts{n, 1} = getsampleusingtime(logsout.get(s1).Values.Thyristor_voltage, tstart, tstop);
    S_amps{n, 1} = getsampleusingtime(logsout.get(s1).Values.Thyristor_current, tstart, tstop);
end